set xlabel "Number of qubits" font ",13"
set ylabel "Time (microseconds)" font ",13"
set pointsize 3.0
set title "Run Time of Grover's Algorithm with Increasing Qubits"
set title font ", 15"
set xrange [4:10]
set yrange [0: 3.5*(10**8)]
set key off
set tics font ", 10"
set style line 1 lc "blue" lw 3  
f(x) =  a*x**(x+b) + c
a = 100000
b = -1
c = 1

fit f(x) 'grovers_time.dat' using 1:2 via a, b, c
plot 'grovers_time.dat' u 1:2, f(x) lw 2 lc "blue"
pause -1